import { Bot, CalendarClock, Clock3, History, Pause, Play, Plus, Save, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader } from "../components/PageHeader";
import { api } from "../services/api";
import { useLanguage } from "../i18n/LanguageContext";
import type { ManagedAgent, SkillInfo } from "../types";

const blank = { name: "", type: "manual" as ManagedAgent["type"], instruction: "", model: "", skills: [] as string[], tools: [] as string[], max_turns: 8, memory_enabled: true, schedule: "", active: true };

export function AgentsPage() {
  const { language, t } = useLanguage();
  const date = (value?: string | null) => value ? new Intl.DateTimeFormat(language, { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : t("Never");
  const [agents, setAgents] = useState<ManagedAgent[]>([]);
  const [skills, setSkills] = useState<SkillInfo[]>([]);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState(blank);
  const [error, setError] = useState("");
  const [runs, setRuns] = useState<Record<string, Array<{ id: string; started_at: string; status: string; summary: string }>>>({});
  const load = () => void Promise.all([api.agents(), api.skills()]).then(([items, skillItems]) => { setAgents(items); setSkills(skillItems); setError(""); }).catch((cause) => setError(cause.message));
  useEffect(load, [language]);
  const create = async () => { try { await api.createAgent(form); setForm(blank); setCreating(false); load(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("Could not create the agent.")); } };
  const toggle = async (agent: ManagedAgent) => { await api.updateAgent(agent.id, { active: !agent.active }); load(); };
  const remove = async (agent: ManagedAgent) => { if (!window.confirm(t("Delete agent “{name}”?", { name: agent.name }))) return; await api.deleteAgent(agent.id); load(); };
  const run = async (agent: ManagedAgent) => { try { await api.runAgent(agent.id); setError(""); window.setTimeout(load, 400); } catch (cause) { setError(cause instanceof Error ? cause.message : t("Could not start the agent.")); } };
  const history = async (agent: ManagedAgent) => { if (runs[agent.id]) { setRuns(({ [agent.id]: _, ...rest }) => rest); return; } try { const items = await api.agentRuns(agent.id); setRuns((current) => ({ ...current, [agent.id]: items })); } catch (cause) { setError(cause instanceof Error ? cause.message : t("Could not load run history.")); } };
  return (
    <section className="page-scroll">
      <PageHeader icon={Bot} eyebrow={t("PERSISTENT OPERATIONS")} title={t("Agents")} description={t("Create manual, recurring and monitoring tasks that survive application restarts.")} actions={<button className="button primary" onClick={() => setCreating(true)}><Plus size={14} />{t("New agent")}</button>} />
      {error && <div className="inline-error">{error}</div>}
      <div className="agent-summary"><article><Bot size={17} /><div><b>{agents.length}</b><span>{t("configured")}</span></div></article><article><Play size={17} /><div><b>{agents.filter((agent) => agent.active).length}</b><span>{t("active")}</span></div></article><article><CalendarClock size={17} /><div><b>{agents.filter((agent) => agent.type !== "manual").length}</b><span>{t("scheduled")}</span></div></article><article><History size={17} /><div><b>{agents.filter((agent) => agent.last_run_at).length}</b><span>{t("have run")}</span></div></article></div>
      <div className="agent-grid">{agents.map((agent) => <article className="agent-card" key={agent.id}><header><span className={`agent-state ${agent.active ? "active" : "paused"}`}><Bot size={17} /></span><div><small>{t(agent.type)}</small><h3>{agent.name}</h3></div><button className={`switch ${agent.active ? "on" : ""}`} onClick={() => void toggle(agent)}><i /></button></header><p>{agent.instruction}</p><div className="chip-list">{agent.skills.map((skill) => <span key={skill}>{skill}</span>)}{!agent.skills.length && <span>{t("automatic skills")}</span>}</div><dl><div><dt>{t("Model")}</dt><dd>{agent.model || t("Runtime default")}</dd></div><div><dt>{t("Schedule")}</dt><dd>{agent.schedule || t("Manual")}</dd></div><div><dt>{t("Last run")}</dt><dd>{date(agent.last_run_at)}</dd></div><div><dt>{t("Next run")}</dt><dd>{date(agent.next_run_at)}</dd></div></dl>{runs[agent.id] && <div className="agent-runs">{runs[agent.id].map((item) => <div key={item.id}><span>{date(item.started_at)}</span><b>{t(item.status)}</b><p>{item.summary || t("Running…")}</p></div>)}{!runs[agent.id].length && <p>{t("No runs yet.")}</p>}</div>}<footer><span className={`status-badge ${agent.state}`}>{t(agent.state)}</span><button title={t("Run now")} disabled={agent.state === "running"} onClick={() => void run(agent)}><Play size={14} /></button><button title={t("Run history")} onClick={() => void history(agent)}><History size={14} /></button><button title={agent.active ? t("Pause") : t("Resume")} onClick={() => void toggle(agent)}>{agent.active ? <Pause size={14} /> : <Play size={14} />}</button><button className="danger-link" title={t("Delete")} onClick={() => void remove(agent)}><Trash2 size={14} /></button></footer></article>)}</div>
      {!agents.length && <div className="large-empty"><span><Bot size={24} /></span><h2>{t("No persistent agents yet")}</h2><p>{t("Create a daily brief, weekly task or long-running monitor. Definitions and run history remain in local SQLite.")}</p><button className="button primary" onClick={() => setCreating(true)}><Plus size={14} />{t("Create first agent")}</button></div>}
      {creating && <div className="modal-backdrop" onMouseDown={() => setCreating(false)}><section className="agent-dialog" onMouseDown={(event) => event.stopPropagation()}><header><div><small>{t("NEW PERSISTENT AGENT")}</small><h2>{t("Configure agent")}</h2></div><button onClick={() => setCreating(false)}><X size={17} /></button></header><label><span>{t("Name")}</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder={t("Morning system brief")} /></label><div className="field-pair"><label><span>{t("Type")}</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as ManagedAgent["type"] })}><option value="manual">{t("Manual")}</option><option value="daily">{t("Daily")}</option><option value="weekly">{t("Weekly")}</option><option value="interval">{t("Interval")}</option><option value="monitor">{t("Monitor")}</option></select></label><label><span>{t("Maximum turns")}</span><input type="number" min={1} max={32} value={form.max_turns} onChange={(event) => setForm({ ...form, max_turns: Number(event.target.value) })} /></label></div><label><span>{t("Instruction")}</span><textarea rows={5} value={form.instruction} onChange={(event) => setForm({ ...form, instruction: event.target.value })} placeholder={t("Describe the outcome and boundaries…")} /></label><label><span>{t("Schedule")}</span><input value={form.schedule} onChange={(event) => setForm({ ...form, schedule: event.target.value })} placeholder={t("daily 08:00 or interval 30m")} /></label><label><span>{t("Skills")}</span><div className="selectable-chips">{skills.map((skill) => <button key={skill.name} className={form.skills.includes(skill.name) ? "selected" : ""} onClick={() => setForm({ ...form, skills: form.skills.includes(skill.name) ? form.skills.filter((name) => name !== skill.name) : [...form.skills, skill.name] })}>{skill.title}</button>)}</div></label><footer><button className="button secondary" onClick={() => setCreating(false)}>{t("Cancel")}</button><button className="button primary" disabled={!form.name.trim() || !form.instruction.trim()} onClick={() => void create()}><Save size={14} />{t("Create agent")}</button></footer></section></div>}
    </section>
  );
}
